### ISSUE TITLE
The -c, --config flags don't work

### ISSUE THREAD

**Issue by tux93** [muesli/mastotool#13]
I want to use different configs for different accounts kept in a `~/.mastotool` folder, when creating the folder, moving the `mastodon.json` file created on the first run and running `mastotool -c .mastotool/$account.json` the authentication process is restarted.   
It doesn't matter if the long or short option is used, nor the full path or relative.

Current workaround is symlinking mastodon.json to the account file I want to use.

**Comment by muesli** [comment]
Released in v0.2.3.
