### ISSUE TITLE
Recent versions (0.2.2+) not working on Ubuntu 16.04/Mint 18

### ISSUE THREAD

**Issue by IzzySoft** [muesli/mastotool#14]
The statically linked one from the 64bit version complains:

    bash: ./mastotool: cannot execute binary file: Exec format error

The one from the Debian package complains:

    ./mastotool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./mastotool)

(present: libc6 2.23 – so the package misses to point out the dependency `libc6 = 2.32`)

Last one working is mastotool v2.2.1.

PS: Ah yuck, the statical one is ARM64, not AMD64 – there is no AMD64. Could you provide one?

**Comment by muesli** [comment]
There is: https://github.com/muesli/mastotool/releases/download/v0.2.3/mastotool_0.2.3_linux_x86_64.tar.gz

However you might run into the same issue there. I'll have to enable cgo-less builds for that.

**Comment by muesli** [comment]
Fixed in `v0.2.4`.

**Comment by IzzySoft** [comment]
Thanks, confirmed working! Repo updated (apt + yum). One question: when installed via apt/yum and called just "via PATH", where will it place its `mastodon.json`? Currently it seems to be either the directory the binary lies in (which, when installed via apt/yum, is not writable for the user) – or the one I'm just in (which would mean I'd have to make sure always to be in the same directory when calling it). I didn't try figuring by "try-and-err", hoping for a clear word :wink:

**Comment by muesli** [comment]
It will always use the current working dir. Should probably store it in an XDG compliant path.

**Comment by IzzySoft** [comment]
Thanks for clarification – that's what I suspected. And yes, such a path would be much preferred – be it `~/.config/mastotool` or even just `~/.mastotool`. There *could* be an overriding option, like `-c <config-to-use>`, especially for folks with multiple accounts.
